spring.application.name=betalyze

spring.datasource.url=jdbc:postgresql://betalyze.postgres.database.azure.com:5432/betalyze
spring.datasource.username=postgres
spring.datasource.password=@Andorla0204
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

firebase.config.path=./firebase-service-account.json

springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.enabled=true

logging.level.root=ERROR
logging.level.com.betalyze=DEBUG
logging.level.org.springframework=WARN
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=WARN
logging.level.org.apache.catalina=WARN

server.port=${PORT:8080}
server.error.include-message=always
server.error.include-stacktrace=on_param
