spring:
  application:
    name: betalyze

  datasource:
    url: jdbc:postgresql://betalyze.postgres.database.azure.com:5432/betalyze
    username: postgres
    password: @Andorla0204
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

firebase:
  config:
    path: ./firebase-service-account.json

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: true

logging:
  level:
    root: ERROR
    com.betalyze: DEBUG
    org.springframework: WARN
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.apache.catalina: WARN

server:
  port: 8094
  error:
    include-message: always
    include-stacktrace: on_param
