name: Build and deploy JAR app to Azure Web App - betalyzeapi

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package -U -DskipTests

      - name: Check JAR size
        run: ls -lh target/*.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C065C1891E8464695DE61769F2589E2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_979CD0D663404145B497F898E5B9D6D4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DCB3EF360F148D9B0695D337FE20935 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'betalyzeapi'
          slot-name: 'Production'
          package: '*.jar'
